name: Dispatch
on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -vv -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/HIDE810/anfun/dispatches" -d '{"event_type": "update"}'